=== Shendelzare/arso/com.arso/target/classes/actaCalificacionesDef.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT acta (calificacion+,diligencia*)>
<!ELEMENT calificacion (nif,nombre?,nota)>
<!ELEMENT nif (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nota (#PCDATA)>
<!ELEMENT diligencia (nif, nombre?, nota)>

<!ATTLIST acta
	asignatura NMTOKEN #REQUIRED
	convocatoria (febrero|junio|julio) #REQUIRED
	curso NMTOKEN #REQUIRED>
<!ATTLIST diligencia
	fecha CDATA #REQUIRED
	extraordinaria (si|no) "no">

=== Shendelzare/arso/com.arso/target/classes/acta.xml
<?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE acta SYSTEM "actaCalificacionesDef.dtd">
  
<acta convocatoria="febrero" curso="2020" asignatura="1902">
  	<calificacion>
        	<nif>23322156M</nif>
        	<nota>10</nota>
  	</calificacion>  	 
  	<calificacion>
        	<nif>13322156M</nif>
        	<nombre>Pepe</nombre>  
        	<nota>8</nota>
  	</calificacion>  
  	<diligencia fecha="2021-02-05">
        	<nif>13322156M</nif>
        	<nota>9</nota>	
  	</diligencia>
</acta>
